# Generated by Django 5.0.6 on 2024-06-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0013_alter_post_content_alter_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVnpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_desc', models.TextField()),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
            ],
        ),
    ]
