# Generated by Django 5.0.6 on 2024-06-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_active_slide_active_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
