# Generated by Django 5.0.6 on 2024-06-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_slide_content_alter_slide_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
