# Generated by Django 5.0.6 on 2024-06-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_adress_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adress',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
