# Generated by Django 5.0.6 on 2024-06-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_order_product_order_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='gia',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='sale',
            new_name='sale_price',
        ),
    ]
