# Generated by Django 5.0.6 on 2024-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_product',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='myapp.cartitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('wallet', 'Thanh toán qua ví điện tử')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Chưa thanh toán', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cxn', 'Chờ xác nhận'), ('clh', 'Chờ lấy hàng'), ('cgh', 'Chờ giao hàng'), ('dg', 'Đã giao'), ('dh', 'Đã hủy')], default='cxn', max_length=20),
        ),
        migrations.DeleteModel(
            name='Order_detail',
        ),
    ]
