# Generated by Django 5.0.6 on 2024-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_order_items_order_order_code_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/users/%Y/%m'),
        ),
    ]
